// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID      int64
	Actor   string
	Action  string
	Target  *string
	Payload []byte
	At      pgtype.Timestamptz
}

type BallotEntry struct {
	SeasonID  pgtype.UUID
	PersonID  pgtype.UUID
	MovieID   pgtype.UUID
	Rank      int32
	CreatedAt pgtype.Timestamptz
}

type Movie struct {
	ID          pgtype.UUID
	SeasonID    pgtype.UUID
	SubmittedBy pgtype.UUID
	Title       string
	Year        *int32
	TmdbID      *int32
	TrailerUrl  *string
	Description string
	Hidden      bool
	CreatedAt   pgtype.Timestamptz
}

type Person struct {
	ID              pgtype.UUID
	Email           string
	EmailNormalized string
	GoogleSub       *string
	DisplayName     string
	CreatedAt       pgtype.Timestamptz
}

type Result struct {
	SeasonID      pgtype.UUID
	WinnerMovieID pgtype.UUID
	Rounds        []byte
	TalliedAt     pgtype.Timestamptz
}

type Season struct {
	ID                 pgtype.UUID
	Year               int32
	Name               string
	ThemePack          string
	SubmitOpensAt      pgtype.Timestamptz
	VoteOpensAt        pgtype.Timestamptz
	VoteClosesAt       pgtype.Timestamptz
	LockedAt           pgtype.Timestamptz
	State              string
	DefaultSubmitLimit int32
	CreatedAt          pgtype.Timestamptz
}

type SeasonMember struct {
	SeasonID    pgtype.UUID
	PersonID    pgtype.UUID
	IsAdmin     bool
	SubmitLimit *int32
	CreatedAt   pgtype.Timestamptz
}
