// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Backs the per-person submission cap. Hidden rows must not count: otherwise
	// withdrawing a film and submitting a different one would permanently burn a
	// slot.
	CountPersonMoviesInSeason(ctx context.Context, arg CountPersonMoviesInSeasonParams) (int64, error)
	// Append-only. Nothing here reads the log yet: the admin feed is its own
	// ticket. What exists is the write, because an action that changes a season or
	// takes a film off the board has to leave a trace at the moment it happens --
	// a logger writes to stdout and stdout is rotated away, and migration 00007
	// exists precisely so these events outlive the rows they describe.
	// actor is text and deliberately not a foreign key (see migration 00007): it
	// records the email of whoever did it, or 'system' when nobody did. target is
	// a free string rather than a uuid column for the same reason -- it has to
	// keep naming a row that may later be gone.
	//
	// payload is jsonb and arrives as raw bytes, so a caller marshals its own
	// struct. That keeps the shape of a payload next to the action that writes it
	// instead of in a union type here that every new action widens.
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	// The production season-creation path (ticket D3). Production is never seeded:
	// an admin types a year, a name and two dates into a form, and this is what
	// that form runs.
	//
	// state is a parameter rather than a default because the admin screen decides
	// it: creating a season IS the act of opening it, so the form posts
	// 'submitting'. 'draft' stays reachable for a season being prepared ahead of
	// time, which is what season.state's own DEFAULT would have given -- but a
	// default here would mean the ordinary case had to remember to override it,
	// and the ordinary case is the one that must not need remembering.
	//
	// No locked_at parameter, and none is possible: season_locked_has_timestamp
	// says a season is locked if and only if it records when, so a season created
	// directly into 'locked' would be an archive with no ballots in it. The CHECK
	// refuses it, which is the right answer.
	//
	// year is UNIQUE (season_year_key), so a second attempt for the same year
	// comes back as SQLSTATE 23505 and the handler turns it into a sentence.
	CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error)
	// Removing someone from a season's whitelist. This cascades to their ballot
	// for that season (ballot_entry references season_member), but not to their
	// submissions -- movie.submitted_by is ON DELETE RESTRICT against person and
	// is not reached from here at all, so a removed member's films stay on the
	// slate. Hide them explicitly if that is what is wanted.
	DeleteSeasonMember(ctx context.Context, arg DeleteSeasonMemberParams) error
	// "Current" is the newest season that has left draft. A draft season is not
	// visible to anyone but an admin, and it must not shadow last year's locked
	// season on the front page -- so a half-configured 2027 cannot hide 2026.
	// Admins reach a draft season through GetSeasonByYear or ListSeasons.
	GetCurrentSeason(ctx context.Context) (Season, error)
	// The whole reason the override lives on the membership row: NULL means "use
	// the season default". Resolving that COALESCE here, once, is what stops every
	// handler from reimplementing it -- and reimplementing it wrongly, because the
	// obvious wrong version treats a NULL override as 0 and silently bans the
	// person from submitting.
	//
	// An explicit 0 override is honoured: that person may vote but may not submit.
	// No rows means not a member of this season, which is a different answer from
	// a limit of 0.
	GetEffectiveSubmitLimit(ctx context.Context, arg GetEffectiveSubmitLimitParams) (int32, error)
	// Submissions. `hidden` is a soft delete everywhere: a hidden movie is not on
	// the slate, does not count against its submitter's cap, and does not block a
	// resubmission of the same TMDB id -- but the ballot rows that ranked it
	// survive.
	GetMovie(ctx context.Context, id uuid.UUID) (Movie, error)
	// person is the identity spine. These queries cover sign-in only; everything
	// that decides whether a person may do something lives in season_member.
	GetPerson(ctx context.Context, id uuid.UUID) (Person, error)
	// The whitelist lookup. Admins add people by email before those people have
	// ever signed in, so this is how a brand new Google identity finds the row
	// that was already waiting for it.
	GetPersonByEmailNormalized(ctx context.Context, emailNormalized string) (Person, error)
	// The returning-visitor lookup, and the reason a person can change their email
	// address without becoming a new person. Sign-in tries this first.
	//
	// The cast forces a non-null parameter. The column is nullable, but looking a
	// person up by a null subject is not a thing we ever want to do -- and in SQL
	// it would quietly match nothing rather than fail, so making it unrepresentable
	// in Go is the honest version.
	GetPersonByGoogleSub(ctx context.Context, googleSub string) (Person, error)
	// One row per year. Past seasons stay browsable forever, so the list queries
	// here are what the archive is built from.
	GetSeason(ctx context.Context, id uuid.UUID) (Season, error)
	GetSeasonByYear(ctx context.Context, year int32) (Season, error)
	// The per-year whitelist. Membership is what gates sign-in, admin is per
	// season, and submit_limit is a per-person override of the season default.
	// Returns no rows for a person who is not in this season, which is the
	// authorisation answer as well as the lookup result.
	GetSeasonMember(ctx context.Context, arg GetSeasonMemberParams) (SeasonMember, error)
	// A person's own live submissions. Hidden rows are excluded so that this list
	// and CountPersonMoviesInSeason always agree -- if the page shows two films,
	// the cap has counted two.
	ListPersonMoviesForSeason(ctx context.Context, arg ListPersonMoviesForSeasonParams) ([]Movie, error)
	// The archive. Drafts are excluded here rather than filtered in a handler so
	// that forgetting the filter is not a way to leak next year's season.
	ListPublishedSeasons(ctx context.Context) ([]Season, error)
	// The admin whitelist page. Joined to person because a list of uuids is not a
	// whitelist anyone can read; email is the column an admin actually recognises
	// and is therefore also the sort key.
	ListSeasonMembers(ctx context.Context, seasonID uuid.UUID) ([]ListSeasonMembersRow, error)
	// Every season including drafts. Admin only -- the public archive uses
	// ListPublishedSeasons.
	ListSeasons(ctx context.Context) ([]Season, error)
	// The slate: what the submissions page shows and what the ballot is built
	// from. Ordered by submission time with an id tiebreak so the list is stable
	// across page loads.
	ListVisibleMoviesForSeason(ctx context.Context, seasonID uuid.UUID) ([]Movie, error)
	// The slate as a page renders it: every live submission, with the name to
	// credit it to.
	//
	// ListVisibleMoviesForSeason returns the same rows without the join and stays
	// as it is -- the tally has no use for a display name. This one exists because
	// the only alternative on the page side is a person lookup per card.
	//
	// An INNER JOIN is safe here, and that is a property of the schema rather than
	// an assumption: movie.submitted_by is NOT NULL and ON DELETE RESTRICT against
	// person, so the submitter row cannot be missing and the join cannot silently
	// drop a film off the slate.
	//
	// Joined to person and deliberately NOT to season_member. Someone removed from
	// the season keeps their films on the slate (see DeleteSeasonMember), and
	// joining through the roster would make those films lose their name -- or,
	// inner-joined, vanish.
	//
	// display_name may be '': a whitelisted person who has never signed in has no
	// name at all. That blank is the page's to handle (MovieCard.SubmitterLabel),
	// not this query's to paper over -- substituting the email here would put an
	// address on a public page.
	ListVisibleMoviesWithSubmitterForSeason(ctx context.Context, seasonID uuid.UUID) ([]ListVisibleMoviesWithSubmitterForSeasonRow, error)
	// GetEffectiveSubmitLimit, plus the row lock that makes the submission cap
	// actually hold.
	//
	// The cap is enforced by counting a person's live submissions and then
	// inserting one more. Those are two statements, and putting them in one
	// transaction does NOT by itself make the pair safe: at READ COMMITTED -- the
	// default, and what pgxpool hands out -- two concurrent submissions from the
	// same person both read a count of 1, both pass a limit of 2, and both
	// commit. The transaction gives atomicity, not mutual exclusion.
	//
	// FOR UPDATE is what supplies the mutual exclusion. The second transaction
	// blocks here until the first commits, and then counts the row the first one
	// inserted. It is taken on the membership row because that is the thing the
	// cap is per: one lock per person per season, so two different people
	// submitting at the same moment never wait on each other.
	//
	// OF season_member is load-bearing. A bare FOR UPDATE would also lock the
	// joined season row, which would serialise every submission in the season
	// behind one another and block an admin editing the season's windows for as
	// long as any submission is open.
	//
	// Everything else is GetEffectiveSubmitLimit's contract, unchanged and for the
	// same reasons: the COALESCE is resolved here so no handler reimplements it,
	// an explicit 0 override is honoured ("may vote, may not submit"), and no rows
	// means not a member of this season -- which is a different answer from a
	// limit of 0, and is also the authorisation answer, since nothing in the
	// schema stops a non-member's INSERT into movie.
	LockSubmitLimitForUpdate(ctx context.Context, arg LockSubmitLimitForUpdateParams) (int32, error)
	// The soft delete, and its undo. There is deliberately no DELETE FROM movie:
	// ballot_entry's foreign key would block it anyway, which is the point.
	SetMovieHidden(ctx context.Context, arg SetMovieHiddenParams) (Movie, error)
	// Scoped by id alone; who may edit a submission is an authorisation question
	// the handler answers, not something to smuggle into a WHERE clause.
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	// The google_sub path of sign-in: the person is already known, but Google may
	// have handed us a new email address or display name. Without this the
	// GetPersonByGoogleSub lookup would be read-only and an email change would
	// never be recorded.
	UpdatePersonIdentity(ctx context.Context, arg UpdatePersonIdentityParams) (Person, error)
	// Re-dating a season after it exists, which is the half of ticket D3 that gets
	// used more than once: the submission deadline slips every year.
	//
	// Deliberately NOT a superset of UpdateSeasonState. state and locked_at have to
	// move together and that query derives locked_at so no caller can construct a
	// combination the CHECK refuses; folding the two together here would hand every
	// date edit the ability to lock a season by accident.
	//
	// year is not updatable either. It is the season's identity -- the UNIQUE key
	// the archive is browsed by -- and "the 2026 season is now 2027" is a different
	// operation from "the 2026 deadline moved", with different consequences for
	// every link already pasted into the group chat.
	UpdateSeasonDetails(ctx context.Context, arg UpdateSeasonDetailsParams) (Season, error)
	// state and locked_at have to move together: the season_locked_has_timestamp
	// CHECK says a season is locked if and only if it records when it locked.
	// Deriving locked_at here means no caller can construct a state change the
	// database will reject. COALESCE preserves the original lock time if a locked
	// season is re-locked.
	UpdateSeasonState(ctx context.Context, arg UpdateSeasonStateParams) (Season, error)
	// All three are nullable: a season can be created before its dates are
	// decided, and clearing a window back to NULL is a legitimate edit.
	UpdateSeasonWindows(ctx context.Context, arg UpdateSeasonWindowsParams) (Season, error)
	// The email path of sign-in: used when no row matched google_sub, which means
	// either a first sign-in against a whitelisted email or a genuinely new person.
	//
	// The WHERE on the DO UPDATE is an account-takeover guard, not a tidy-up.
	// Without it, a Google identity that has never signed in here misses the
	// google_sub lookup, falls through to this query, conflicts on a whitelisted
	// email and overwrites the stored google_sub -- inheriting that person's
	// submissions, ballots and is_admin flag. The victim's next sign-in then also
	// misses the sub lookup and clobbers it back, so two identities ping-pong on
	// one row. Google ties sub to the account object rather than to the address,
	// so a recreated account or a recycled address is enough to trigger it.
	// Reproduced end to end; TestSignInTakeoverIsBlocked replays it.
	//
	// person_google_sub_key UNIQUE (google_sub) does NOT prevent this. That is the
	// trap in reading the constraint list and assuming it is covered: the incoming
	// sub exists nowhere else in the table, so the unique index is satisfied by
	// MOVING it onto the victim's row. It only stops two ROWS holding the same sub.
	//
	// So the update applies to a row only when it is unclaimed (google_sub IS NULL:
	// whitelisted, never signed in) or already owned by this same subject. A
	// genuine collision updates nothing, RETURNING yields no row, and :one surfaces
	// pgx.ErrNoRows. THE CALLER MUST NOT READ THAT AS "person not found": it means
	// "this email belongs to a different Google identity", which is refuse-sign-in
	// and escalate to an admin.
	//
	// google_sub is a non-null parameter even though the column is nullable. The
	// column must allow null for whitelisted rows that have never signed in, but a
	// sign-in always carries a subject: internal/auth rejects an ID token whose sub
	// is absent or empty (ErrNoSubject) before it can reach here. That matters,
	// because with a nullable parameter `person.google_sub = EXCLUDED.google_sub`
	// evaluates to NULL rather than true for an already-linked person, the update
	// silently skips, and a legitimate sign-in is misreported as a collision. If
	// the ErrNoSubject gate is ever removed, this parameter has to go back to
	// sqlc.narg and the guard needs a third arm, `OR EXCLUDED.google_sub IS NULL`.
	UpsertPersonOnSignIn(ctx context.Context, arg UpsertPersonOnSignInParams) (Person, error)
	// Adding someone who is already a member updates their flags rather than
	// failing, so an admin re-pasting a whitelist is idempotent.
	//
	// submit_limit is written through as-is, NULL included: passing NULL is how an
	// admin removes an override and puts someone back on the season default.
	UpsertSeasonMember(ctx context.Context, arg UpsertSeasonMemberParams) (SeasonMember, error)
}

var _ Querier = (*Queries)(nil)
