// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Backs the per-person submission cap. Hidden rows must not count: otherwise
	// withdrawing a film and submitting a different one would permanently burn a
	// slot.
	CountPersonMoviesInSeason(ctx context.Context, arg CountPersonMoviesInSeasonParams) (int64, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	// Removing someone from a season's whitelist. This cascades to their ballot
	// for that season (ballot_entry references season_member), but not to their
	// submissions -- movie.submitted_by is ON DELETE RESTRICT against person and
	// is not reached from here at all, so a removed member's films stay on the
	// slate. Hide them explicitly if that is what is wanted.
	DeleteSeasonMember(ctx context.Context, arg DeleteSeasonMemberParams) error
	// "Current" is the newest season that has left draft. A draft season is not
	// visible to anyone but an admin, and it must not shadow last year's locked
	// season on the front page -- so a half-configured 2027 cannot hide 2026.
	// Admins reach a draft season through GetSeasonByYear or ListSeasons.
	GetCurrentSeason(ctx context.Context) (Season, error)
	// The whole reason the override lives on the membership row: NULL means "use
	// the season default". Resolving that COALESCE here, once, is what stops every
	// handler from reimplementing it -- and reimplementing it wrongly, because the
	// obvious wrong version treats a NULL override as 0 and silently bans the
	// person from submitting.
	//
	// An explicit 0 override is honoured: that person may vote but may not submit.
	// No rows means not a member of this season, which is a different answer from
	// a limit of 0.
	GetEffectiveSubmitLimit(ctx context.Context, arg GetEffectiveSubmitLimitParams) (int32, error)
	// Submissions. `hidden` is a soft delete everywhere: a hidden movie is not on
	// the slate, does not count against its submitter's cap, and does not block a
	// resubmission of the same TMDB id -- but the ballot rows that ranked it
	// survive.
	GetMovie(ctx context.Context, id pgtype.UUID) (Movie, error)
	// person is the identity spine. These queries cover sign-in only; everything
	// that decides whether a person may do something lives in season_member.
	GetPerson(ctx context.Context, id pgtype.UUID) (Person, error)
	// The whitelist lookup. Admins add people by email before those people have
	// ever signed in, so this is how a brand new Google identity finds the row
	// that was already waiting for it.
	GetPersonByEmailNormalized(ctx context.Context, emailNormalized string) (Person, error)
	// The returning-visitor lookup, and the reason a person can change their email
	// address without becoming a new person. Sign-in tries this first.
	//
	// The cast forces a non-null parameter. The column is nullable, but looking a
	// person up by a null subject is not a thing we ever want to do -- and in SQL
	// it would quietly match nothing rather than fail, so making it unrepresentable
	// in Go is the honest version.
	GetPersonByGoogleSub(ctx context.Context, googleSub string) (Person, error)
	// One row per year. Past seasons stay browsable forever, so the list queries
	// here are what the archive is built from.
	GetSeason(ctx context.Context, id pgtype.UUID) (Season, error)
	GetSeasonByYear(ctx context.Context, year int32) (Season, error)
	// The per-year whitelist. Membership is what gates sign-in, admin is per
	// season, and submit_limit is a per-person override of the season default.
	// Returns no rows for a person who is not in this season, which is the
	// authorisation answer as well as the lookup result.
	GetSeasonMember(ctx context.Context, arg GetSeasonMemberParams) (SeasonMember, error)
	// A person's own live submissions. Hidden rows are excluded so that this list
	// and CountPersonMoviesInSeason always agree -- if the page shows two films,
	// the cap has counted two.
	ListPersonMoviesForSeason(ctx context.Context, arg ListPersonMoviesForSeasonParams) ([]Movie, error)
	// The archive. Drafts are excluded here rather than filtered in a handler so
	// that forgetting the filter is not a way to leak next year's season.
	ListPublishedSeasons(ctx context.Context) ([]Season, error)
	// The admin whitelist page. Joined to person because a list of uuids is not a
	// whitelist anyone can read; email is the column an admin actually recognises
	// and is therefore also the sort key.
	ListSeasonMembers(ctx context.Context, seasonID pgtype.UUID) ([]ListSeasonMembersRow, error)
	// Every season including drafts. Admin only -- the public archive uses
	// ListPublishedSeasons.
	ListSeasons(ctx context.Context) ([]Season, error)
	// The slate: what the submissions page shows and what the ballot is built
	// from. Ordered by submission time with an id tiebreak so the list is stable
	// across page loads.
	ListVisibleMoviesForSeason(ctx context.Context, seasonID pgtype.UUID) ([]Movie, error)
	// The soft delete, and its undo. There is deliberately no DELETE FROM movie:
	// ballot_entry's foreign key would block it anyway, which is the point.
	SetMovieHidden(ctx context.Context, arg SetMovieHiddenParams) (Movie, error)
	// Scoped by id alone; who may edit a submission is an authorisation question
	// the handler answers, not something to smuggle into a WHERE clause.
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	// The google_sub path of sign-in: the person is already known, but Google may
	// have handed us a new email address or display name. Without this the
	// GetPersonByGoogleSub lookup would be read-only and an email change would
	// never be recorded.
	UpdatePersonIdentity(ctx context.Context, arg UpdatePersonIdentityParams) (Person, error)
	// state and locked_at have to move together: the season_locked_has_timestamp
	// CHECK says a season is locked if and only if it records when it locked.
	// Deriving locked_at here means no caller can construct a state change the
	// database will reject. COALESCE preserves the original lock time if a locked
	// season is re-locked.
	UpdateSeasonState(ctx context.Context, arg UpdateSeasonStateParams) (Season, error)
	// All three are nullable: a season can be created before its dates are
	// decided, and clearing a window back to NULL is a legitimate edit.
	UpdateSeasonWindows(ctx context.Context, arg UpdateSeasonWindowsParams) (Season, error)
	// The email path of sign-in: used when no row matched google_sub, which means
	// either a first sign-in against a whitelisted email or a genuinely new person.
	//
	// google_sub is COALESCEd so that a null subject (should not happen, but the
	// column allows it) cannot unlink an already-linked person, and display_name
	// falls back to the stored value so a provider that returns no name does not
	// blank out one we already had.
	UpsertPersonOnSignIn(ctx context.Context, arg UpsertPersonOnSignInParams) (Person, error)
	// Adding someone who is already a member updates their flags rather than
	// failing, so an admin re-pasting a whitelist is idempotent.
	//
	// submit_limit is written through as-is, NULL included: passing NULL is how an
	// admin removes an override and puts someone back on the season default.
	UpsertSeasonMember(ctx context.Context, arg UpsertSeasonMemberParams) (SeasonMember, error)
}

var _ Querier = (*Queries)(nil)
