// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season_member.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSeasonMember = `-- name: DeleteSeasonMember :exec
DELETE FROM season_member
WHERE season_id = $1
  AND person_id = $2
`

type DeleteSeasonMemberParams struct {
	SeasonID pgtype.UUID
	PersonID pgtype.UUID
}

// Removing someone from a season's whitelist. This cascades to their ballot
// for that season (ballot_entry references season_member), but not to their
// submissions -- movie.submitted_by is ON DELETE RESTRICT against person and
// is not reached from here at all, so a removed member's films stay on the
// slate. Hide them explicitly if that is what is wanted.
func (q *Queries) DeleteSeasonMember(ctx context.Context, arg DeleteSeasonMemberParams) error {
	_, err := q.db.Exec(ctx, deleteSeasonMember, arg.SeasonID, arg.PersonID)
	return err
}

const getEffectiveSubmitLimit = `-- name: GetEffectiveSubmitLimit :one
SELECT COALESCE(season_member.submit_limit, season.default_submit_limit)::integer
    AS effective_submit_limit
FROM season_member
JOIN season ON season.id = season_member.season_id
WHERE season_member.season_id = $1
  AND season_member.person_id = $2
`

type GetEffectiveSubmitLimitParams struct {
	SeasonID pgtype.UUID
	PersonID pgtype.UUID
}

// The whole reason the override lives on the membership row: NULL means "use
// the season default". Resolving that COALESCE here, once, is what stops every
// handler from reimplementing it -- and reimplementing it wrongly, because the
// obvious wrong version treats a NULL override as 0 and silently bans the
// person from submitting.
//
// An explicit 0 override is honoured: that person may vote but may not submit.
// No rows means not a member of this season, which is a different answer from
// a limit of 0.
func (q *Queries) GetEffectiveSubmitLimit(ctx context.Context, arg GetEffectiveSubmitLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, getEffectiveSubmitLimit, arg.SeasonID, arg.PersonID)
	var effective_submit_limit int32
	err := row.Scan(&effective_submit_limit)
	return effective_submit_limit, err
}

const getSeasonMember = `-- name: GetSeasonMember :one

SELECT season_id, person_id, is_admin, submit_limit, created_at FROM season_member
WHERE season_id = $1
  AND person_id = $2
`

type GetSeasonMemberParams struct {
	SeasonID pgtype.UUID
	PersonID pgtype.UUID
}

// The per-year whitelist. Membership is what gates sign-in, admin is per
// season, and submit_limit is a per-person override of the season default.
// Returns no rows for a person who is not in this season, which is the
// authorisation answer as well as the lookup result.
func (q *Queries) GetSeasonMember(ctx context.Context, arg GetSeasonMemberParams) (SeasonMember, error) {
	row := q.db.QueryRow(ctx, getSeasonMember, arg.SeasonID, arg.PersonID)
	var i SeasonMember
	err := row.Scan(
		&i.SeasonID,
		&i.PersonID,
		&i.IsAdmin,
		&i.SubmitLimit,
		&i.CreatedAt,
	)
	return i, err
}

const listSeasonMembers = `-- name: ListSeasonMembers :many
SELECT
    season_member.season_id, season_member.person_id, season_member.is_admin, season_member.submit_limit, season_member.created_at,
    person.email,
    person.email_normalized,
    person.display_name
FROM season_member
JOIN person ON person.id = season_member.person_id
WHERE season_member.season_id = $1
ORDER BY person.email
`

type ListSeasonMembersRow struct {
	SeasonMember    SeasonMember
	Email           string
	EmailNormalized string
	DisplayName     string
}

// The admin whitelist page. Joined to person because a list of uuids is not a
// whitelist anyone can read; email is the column an admin actually recognises
// and is therefore also the sort key.
func (q *Queries) ListSeasonMembers(ctx context.Context, seasonID pgtype.UUID) ([]ListSeasonMembersRow, error) {
	rows, err := q.db.Query(ctx, listSeasonMembers, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonMembersRow{}
	for rows.Next() {
		var i ListSeasonMembersRow
		if err := rows.Scan(
			&i.SeasonMember.SeasonID,
			&i.SeasonMember.PersonID,
			&i.SeasonMember.IsAdmin,
			&i.SeasonMember.SubmitLimit,
			&i.SeasonMember.CreatedAt,
			&i.Email,
			&i.EmailNormalized,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSeasonMember = `-- name: UpsertSeasonMember :one
INSERT INTO season_member (season_id, person_id, is_admin, submit_limit)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (season_id, person_id) DO UPDATE
SET is_admin     = EXCLUDED.is_admin,
    submit_limit = EXCLUDED.submit_limit
RETURNING season_id, person_id, is_admin, submit_limit, created_at
`

type UpsertSeasonMemberParams struct {
	SeasonID    pgtype.UUID
	PersonID    pgtype.UUID
	IsAdmin     bool
	SubmitLimit *int32
}

// Adding someone who is already a member updates their flags rather than
// failing, so an admin re-pasting a whitelist is idempotent.
//
// submit_limit is written through as-is, NULL included: passing NULL is how an
// admin removes an override and puts someone back on the season default.
func (q *Queries) UpsertSeasonMember(ctx context.Context, arg UpsertSeasonMemberParams) (SeasonMember, error) {
	row := q.db.QueryRow(ctx, upsertSeasonMember,
		arg.SeasonID,
		arg.PersonID,
		arg.IsAdmin,
		arg.SubmitLimit,
	)
	var i SeasonMember
	err := row.Scan(
		&i.SeasonID,
		&i.PersonID,
		&i.IsAdmin,
		&i.SubmitLimit,
		&i.CreatedAt,
	)
	return i, err
}
