// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentSeason = `-- name: GetCurrentSeason :one
SELECT id, year, name, theme_pack, submit_opens_at, vote_opens_at, vote_closes_at, locked_at, state, default_submit_limit, created_at FROM season
WHERE state <> 'draft'
ORDER BY year DESC
LIMIT 1
`

// "Current" is the newest season that has left draft. A draft season is not
// visible to anyone but an admin, and it must not shadow last year's locked
// season on the front page -- so a half-configured 2027 cannot hide 2026.
// Admins reach a draft season through GetSeasonByYear or ListSeasons.
func (q *Queries) GetCurrentSeason(ctx context.Context) (Season, error) {
	row := q.db.QueryRow(ctx, getCurrentSeason)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Name,
		&i.ThemePack,
		&i.SubmitOpensAt,
		&i.VoteOpensAt,
		&i.VoteClosesAt,
		&i.LockedAt,
		&i.State,
		&i.DefaultSubmitLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one

SELECT id, year, name, theme_pack, submit_opens_at, vote_opens_at, vote_closes_at, locked_at, state, default_submit_limit, created_at FROM season
WHERE id = $1
`

// One row per year. Past seasons stay browsable forever, so the list queries
// here are what the archive is built from.
func (q *Queries) GetSeason(ctx context.Context, id uuid.UUID) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Name,
		&i.ThemePack,
		&i.SubmitOpensAt,
		&i.VoteOpensAt,
		&i.VoteClosesAt,
		&i.LockedAt,
		&i.State,
		&i.DefaultSubmitLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getSeasonByYear = `-- name: GetSeasonByYear :one
SELECT id, year, name, theme_pack, submit_opens_at, vote_opens_at, vote_closes_at, locked_at, state, default_submit_limit, created_at FROM season
WHERE year = $1
`

func (q *Queries) GetSeasonByYear(ctx context.Context, year int32) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByYear, year)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Name,
		&i.ThemePack,
		&i.SubmitOpensAt,
		&i.VoteOpensAt,
		&i.VoteClosesAt,
		&i.LockedAt,
		&i.State,
		&i.DefaultSubmitLimit,
		&i.CreatedAt,
	)
	return i, err
}

const listPublishedSeasons = `-- name: ListPublishedSeasons :many
SELECT id, year, name, theme_pack, submit_opens_at, vote_opens_at, vote_closes_at, locked_at, state, default_submit_limit, created_at FROM season
WHERE state <> 'draft'
ORDER BY year DESC
`

// The archive. Drafts are excluded here rather than filtered in a handler so
// that forgetting the filter is not a way to leak next year's season.
func (q *Queries) ListPublishedSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.Query(ctx, listPublishedSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Name,
			&i.ThemePack,
			&i.SubmitOpensAt,
			&i.VoteOpensAt,
			&i.VoteClosesAt,
			&i.LockedAt,
			&i.State,
			&i.DefaultSubmitLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, year, name, theme_pack, submit_opens_at, vote_opens_at, vote_closes_at, locked_at, state, default_submit_limit, created_at FROM season
ORDER BY year DESC
`

// Every season including drafts. Admin only -- the public archive uses
// ListPublishedSeasons.
func (q *Queries) ListSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Name,
			&i.ThemePack,
			&i.SubmitOpensAt,
			&i.VoteOpensAt,
			&i.VoteClosesAt,
			&i.LockedAt,
			&i.State,
			&i.DefaultSubmitLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeasonState = `-- name: UpdateSeasonState :one
UPDATE season
SET state = $1,
    locked_at = CASE
        WHEN $1 = 'locked' THEN COALESCE(locked_at, now())
        ELSE NULL
    END
WHERE id = $2
RETURNING id, year, name, theme_pack, submit_opens_at, vote_opens_at, vote_closes_at, locked_at, state, default_submit_limit, created_at
`

type UpdateSeasonStateParams struct {
	State string
	ID    uuid.UUID
}

// state and locked_at have to move together: the season_locked_has_timestamp
// CHECK says a season is locked if and only if it records when it locked.
// Deriving locked_at here means no caller can construct a state change the
// database will reject. COALESCE preserves the original lock time if a locked
// season is re-locked.
func (q *Queries) UpdateSeasonState(ctx context.Context, arg UpdateSeasonStateParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeasonState, arg.State, arg.ID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Name,
		&i.ThemePack,
		&i.SubmitOpensAt,
		&i.VoteOpensAt,
		&i.VoteClosesAt,
		&i.LockedAt,
		&i.State,
		&i.DefaultSubmitLimit,
		&i.CreatedAt,
	)
	return i, err
}

const updateSeasonWindows = `-- name: UpdateSeasonWindows :one
UPDATE season
SET submit_opens_at = $1,
    vote_opens_at   = $2,
    vote_closes_at  = $3
WHERE id = $4
RETURNING id, year, name, theme_pack, submit_opens_at, vote_opens_at, vote_closes_at, locked_at, state, default_submit_limit, created_at
`

type UpdateSeasonWindowsParams struct {
	SubmitOpensAt pgtype.Timestamptz
	VoteOpensAt   pgtype.Timestamptz
	VoteClosesAt  pgtype.Timestamptz
	ID            uuid.UUID
}

// All three are nullable: a season can be created before its dates are
// decided, and clearing a window back to NULL is a legitimate edit.
func (q *Queries) UpdateSeasonWindows(ctx context.Context, arg UpdateSeasonWindowsParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeasonWindows,
		arg.SubmitOpensAt,
		arg.VoteOpensAt,
		arg.VoteClosesAt,
		arg.ID,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Name,
		&i.ThemePack,
		&i.SubmitOpensAt,
		&i.VoteOpensAt,
		&i.VoteClosesAt,
		&i.LockedAt,
		&i.State,
		&i.DefaultSubmitLimit,
		&i.CreatedAt,
	)
	return i, err
}
